#!/bin/bash

#SBATCH --job-name=VGG_size___RUN__         # the name of your job
#SBATCH --export=NONE               # Start with a clean environment
#SBATCH --nodes=1                   # the number of nodes you want to reserve
#SBATCH --gres=gpu:4 
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=6       
#SBATCH --mem=100G                   # how much memory is needed per node (units can be: K, M, G, T)
#SBATCH --partition=gpu2080          # on which partition to submit the job
#SBATCH --time=48:00:00             # the max wallclock time (time limit your job will run)
#SBATCH --output=output.dat         # the file where output is written to (stdout & stderr)
#SBATCH --mail-type=FAIL             # receive an email when your job starts, finishes normally or is aborted
#SBATCH --mail-user=m_beck52@uni-muenster.de # your mail address
#SBATCH --nice=80
 
export GPUS_PER_NODE=4

# The first hostname is the master address
master_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_ADDR=$master_addr
export MASTER_PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')
export WORLD_SIZE=$((SLURM_JOB_NUM_NODES*GPUS_PER_NODE))

# START THE APPLICATION
module purge
module load palma/2020b Miniconda3/4.9.2

CONDA_BASE=$(conda info --base)
source $CONDA_BASE/etc/profile.d/conda.sh
conda deactivate
conda activate /home/m/m_beck52/envs/pytorch

srun --export=ALL __EXECUTE__

