#!/bin/bash

 
#SBATCH --job-name=TL___RUN__         # the name of your job
#SBATCH --export=NONE               # Start with a clean environment
#SBATCH --nodes=3                   # the number of nodes you want to reserve
#SBATCH --gres=gpu:1 
#SBATCH --ntasks-per-node=1        # the number of CPU cores per node
#SBATCH --cpus-per-task=12       
#SBATCH --mem=60G                   # how much memory is needed per node (units can be: K, M, G, T)
#SBATCH --partition=gputitanrtx          # on which partition to submit the job
#SBATCH --time=48:00:00             # the max wallclock time (time limit your job will run)
#SBATCH --output=output.dat         # the file where output is written to (stdout & stderr)
#SBATCH --mail-type=FAIL             # receive an email when your job starts, finishes normally or is aborted
#SBATCH --mail-user=m_beck52@uni-muenster.de # your mail address
#SBATCH --nice=80
 
GPUS_PER_NODE=1

# The first hostname is the master address
master_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_ADDR=$master_addr
export MASTER_PORT=12340
export WORLD_SIZE=$((SLURM_JOB_NUM_NODES*GPUS_PER_NODE))
export GPUS_PER_NODE

# START THE APPLICATION
module purge
module load palma/2020b Miniconda3/4.9.2

CONDA_BASE=$(conda info --base)
source $CONDA_BASE/etc/profile.d/conda.sh
conda deactivate
conda activate /home/m/m_beck52/envs/pytorch

srun __EXECUTE__

