#!/bin/bash

#SBATCH --job-name=TL_dist_1         # the name of your job
#SBATCH --export=NONE               # Start with a clean environment
#SBATCH --nodes=3                   # the number of nodes you want to reserve
#SBATCH --gres=gpu:1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=12       
#SBATCH --mem=60G                   # how much memory is needed per node (units can be: K, M, G, T)
#SBATCH --partition=gputitanrtx          # on which partition to submit the job
#SBATCH --time=48:00:00             # the max wallclock time (time limit your job will run)
#SBATCH --output=output.dat         # the file where output is written to (stdout & stderr)
#SBATCH --mail-type=FAIL             # receive an email when your job starts, finishes normally or is aborted
#SBATCH --mail-user=m_beck52@uni-muenster.de # your mail address
#SBATCH --nice=80
 
# The first hostname is the master address
master_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_ADDR=$master_addr
export MASTER_PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')
export WORLD_SIZE=$((SLURM_JOB_NUM_NODES*1))

# START THE APPLICATION
module purge
module load palma/2020b Miniconda3/4.9.2

CONDA_BASE=$(conda info --base)
source $CONDA_BASE/etc/profile.d/conda.sh
conda deactivate
conda activate /home/m/m_beck52/envs/pytorch

srun --export=ALL python3 main.py --logSubDir pre_bs_1024_s_600 --rndSeed --dataset CIFAR100 --model EfficientNet_pre --batchSize 15 --batchSizeMult 68 --learningRate 0.016 --lrScheduler cos --flip --crop --autoAugment --dataThreads 12 --epochs 100 --imageSize 600 --freezeBN --saveCheckpoint --keepLastCheckpoint

