#!/bin/bash
#SBATCH --job-name=name
#SBATCH --export=NONE               # Start with a clean environment
#SBATCH --nodes=1                   # the number of nodes you want to reserve
#SBATCH --gres=gpu:4 
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=8       
#SBATCH --mem=220G                   # how much memory is needed per node (units can be: K, M, G, T)
#SBATCH --partition=gpua100          # on which partition to submit the job
#SBATCH --time=7-00:00:00             # the max wallclock time (time limit your job will run)
#SBATCH --output=output.dat         # the file where output is written to (stdout & stderr)
#SBATCH --mail-type=FAIL             # receive an email when your job starts, finishes normally or is aborted
#SBATCH --mail-user=m_beck52@uni-muenster.de # your mail address
#SBATCH --nice=100

echo "<<<< SLURM VARIABLES >>>>>"
printenv | grep SLURM
echo "<<<< 'scontrol show jobid -dd' OUTPUT >>>>>"
scontrol show jobid -dd $SLURM_JOBID
echo "<<<< GPU INFO >>>>>"
nvidia-smi -L

if ! command -v module &> /dev/null
then
	echo "module not found! using dirty workaround instead"

	echo source /opt/lmod/lmod/init/sh
	export MODULEPATH=/Applic.HPC/modules/PALMA:/Applic.ZIV/modulefiles/
	source /opt/lmod/lmod/init/sh

	echo source /etc/profile
	source /etc/profile

	export HOME=/home/m/m_beck52
fi

# The first hostname is the master address
master_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_ADDR=$master_addr
export MASTER_PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')
export WORLD_SIZE=$((SLURM_JOB_NUM_NODES*SLURM_NTASKS_PER_NODE))

# START THE APPLICATION
module purge
module load palma/2022a  GCCcore/11.3.0
module load Python/3.10.4

srun --export=ALL python3 main.py --rndSeed --logSubDir test  --dataThreads 7 --dataDir /scratch/tmp/m_beck52/data
