logDir = "../logs"
logSubDir = "test"
truncate = false

contin = false
epochs = 200

rndSeed = false
deterministic = false

optimizer = "SGD"
momentum = 0.9 
weightDecay = 0.0005
nesterov = false

saveCheckpoint = false
keepLastCheckpoint = false
checkpointsList = []
saveCheckpointInterval = 0

verbose = false
logEach = 1
metrics = ["learningRate", "loss", "accuracy"]

dataThreads = 6 
dataDir = "~/.datasets"
batchSize = 256 
dataset = "CIFAR100" 
imageSize = 0 
flip = true 
crop = true
cut = true
cutoutProp = 0.5
randAugment = false 
randAugment_magnitude = 10
mixup = false
mixupProp = 0.2

label_smoothing = 0.1

grad_clip_norm = 0.0
normalize = "std"


model = "WRN"
dropout = 0.0
BN = true
depth = 16
widthFactor = 4
ViTPatchsize = 32
ViTSize = "S"

learningRate = 0.5
lrScheduler = ["startRamp", "cos"]

LRScheduler_StartRamp_epochs = 1

LRScheduler_step_steps = 3
LRScheduler_step_gamma = 0.2

LRScheduler_exp_maxDecay = 0.01
LRScheduler_cos_periods = 0.5

LRScheduler_WRN_T0 = 50
LRScheduler_WRN_Tmult = 1.2
