# https://arxiv.org/pdf/2205.01580.pdf
[general]

epochs = 90

optimizer = AdamW
weightDecay = 0.1

saveCheckpoint = True

batchSize = 1024
dataset = ImageNet
imageSize = 224
flip = True 
crop = False
cut = False

label_smoothing = 0.0
grad_clip_norm = 1.0

[models]
model = ViT

ViTPatchsize = 32
ViTSize = S

[learning rate]
learningRate = 0.001
lrScheduler = cosWarmUp
LRScheduler_StartRamp_epochs = 8
