#HPs from SAM paper (except BS=4096)
[general]
epochs = 100
weightDecay = 0.0001

batchSize = 1024
dataset = ImageNet 
imageSize = 224
flip = True 
crop = False
cut = False

[models]
model = resnet
depth = 50

[learning rate]
learningRate = 1.0
