#HPs from SAM paper (except BS=4096)
epochs = 100
weightDecay = 0.0001

batchSize = 1024
dataset = "ImageNet" 
imageSize = 224
flip = true 
crop = false
cut = false

model = "resnet"
depth = 50

learningRate = 1.0
